# Generated by Django 4.2.6 on 2023-10-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbrMachine', models.IntegerField()),
                ('nbrJob', models.IntegerField()),
                ('critere', models.CharField(choices=[('SDST', 'SDST'), ('no-idle', 'no-idle'), ('no-wait', 'no-wait')], max_length=150)),
            ],
        ),
    ]
